### PR TITLE
fix: BootstrapState use custom genesis doc provider

### PR DESCRIPTION
**Pull request by yihuang**
The cosmos-sdk 0.50 genesis doc marshalling not being compatible with the cometbft default one (see https://github.com/cosmos/cosmos-sdk/issues/18477), so we need to support custom genesis doc provider in this public API as well, it's called by the `bootstrap-state` command in cosmos-sdk.

Please backport to 0.38, the SDK 0.50 `bootstrap-state` command is already broken.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by melekes — APPROVED** [review]
Thanks @yihuang ❤️

**Comment by melekes** [comment]
> Please backport to 0.38

Unfortunately, we can't do that because you broke the public Go API.

**Comment by yihuang** [comment]
> > Please backport to 0.38
> 
> Unfortunately, we can't do that because this PR changes the public Go API.

I can introduce a new API `BootstrapStateWithGenProvider` for backporting.

**Comment by yihuang** [comment]
> > > Please backport to 0.38
> > 
> > 
> > Unfortunately, we can't do that because this PR changes the public Go API.
> 
> I can introduce a new API `BootstrapStateWithGenProvider` when backport.

here it is: https://github.com/cometbft/cometbft/pull/2793, WDYT?

**Comment by melekes** [comment]
> > > > Please backport to 0.38
> > > 
> > > 
> > > Unfortunately, we can't do that because this PR changes the public Go API.
> > 
> > 
> > I can introduce a new API `BootstrapStateWithGenProvider` when backport.
> 
> here it is: #2793, WDYT?

Awesome, thanks 👍

**Comment by julienrbrt** [comment]
Can it get backported to v0.38? I see the v1 backport label only.

**Pull request merged**
