### PR TITLE
fix: rollback set incorrect `LastHeightValidatorsChanged`

### PR DESCRIPTION
**Pull request by yihuang**
Closes: #1074

Solution:
- persist the new validator set if changed.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by yihuang** [comment]
Unstale, it's a bug

**Comment by yihuang** [comment]
> Hey @yihuang do you know of any way to test this, or any way to reproduce the bug? That would help us a lot to feel confident about merging this PR.

when rollback, the just rollback-ed `LastHeightValidatorsChanged` field could be wrong, according to the code logic, validator set in the state could be skipped if not changed, it'll reference the height that actually stored the validator set in the field `LastHeightValidatorsChanged`, in current rollback logic, the rollback-ed `LastHeightValidatorsChanged` could be wrong, because it don't guarantee that height do stored the validator set, the patched version will force the rollback-ed version to store the validator set.

**Comment by sergio-mena** [comment]
@yihuang, would you mind?
* Writing a UT that exposes the problem, and demonstrates that this PR fixes it (i.e., UT fails without the fix, and passes with it)
* Adding the info you provided in this PR in the isue itself (#1074) for traceability purposes? (Including [this comment](https://github.com/cometbft/cometbft/pull/1075#issuecomment-1654903582) in the issue's description should suffice)

**Comment by mmsqe** [comment]
I try add a [case](https://github.com/mmsqe/cometbft/compare/1207a24c6c70a18950169501e86ed6872d2009a5...f1bcf8ec94414c9a30b4cb17c2dd54742f9d3bc5) for last height > 2, see if it helps to reproduce.

**Pull request closed without merging**
