### PR TITLE
perf: Remove External Votes From Wal

### PR DESCRIPTION
**Pull request by Eric-Warehime**
Don't write votes coming from external nodes to the WAL.

This will improve both CPU time spent in terms of blocking syscalls and churn in terms of memory allocation for vote buffers being flushed to disk. You can see the effects in these images:
Screenshot 2024-10-25 at 5 07 02 PM

Screenshot 2024-10-25 at 4 55 27 PM

Also adds a new e2e test to better exercise crash recovery. This introduces network-wide perturbations which allow us to kill or restart every node on the network at once. 

Follow ups for this PR:
* I want to introduce some additional configuration options to allow us to specify sleep times for concurrent perturbations.  
The kill and restart in the included test file ends up recovering from each one on the same round without advancing in between them since there is no delay to allow the nodes to produce another round before running the next perturbation.

---

#### PR checklist

- [X] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by tac0turtle** [comment]
ref https://github.com/cometbft/cometbft/issues/3118

**Comment by cason** [comment]
We can't do that.

The consensus algorithm assumes that if an output or action is produced (e.g., we lock a `BlockID` and sign a `Precommit` for it), all the information required for producing this action or output is persisted.

Otherwise, when restarting the node without this information, the node can produce different outputs or actions (e.g., since we haven't locked that `BlockID`, we can sign a `Prevote` for a different value), which is an equivocation.

**Comment by cason** [comment]
By the way, received messages are asynchronously written to the WAL (at almost zero cost).

We only flush the WAL when outputs or actions are produced (e.g., when we sign a `Precommit` in the same example). When this happens, we pay the cost of synchronously writing the output and all inputs that have lead the validator to produce this output (at least the ones that were not synced to disk by the operating system meanwhile).

**Comment by Eric-Warehime** [comment]
>By the way, received messages are asynchronously written to the WAL (at almost zero cost).
> We only flush the WAL when outputs or actions are produced (e.g., when we sign a Precommit in the same example). When this happens, we pay the cost of synchronously writing the output and all inputs that have lead the validator to produce this output (at least the ones that were not synced to disk by the operating system meanwhile).

This is true, there's no fsync for these, but we do call `wal.Write` which is in the critical path for receiving any message in the consensus state. And that call does buffer allocation, protobuf encoding, CRC checksums, etc., which still incurs a cost from both a time and memory perspective, so if we can agree that a change like this is safe, the data suggests that it would have meaningful benefits to Comet's performance.

> Otherwise, when restarting the node without this information, the node can produce different outputs or actions (e.g., since we haven't locked that BlockID, we can sign a Prevote for a different value), which is an equivocation.

I'm not sure that equivocation is the problem here--the PrivVal prevents us from double signing any vote.  We haven't changed that, and we're also still synchronously writing all internal votes to the WAL so we'll always know what's been committed to locally. Also, the `EventDataRoundState` is still being written so our Handshake should at least start from the correct place. 

I think the risk present in this PR is that we're at a round state for which we can never recover the corresponding consensus state since we didn't write down the votes that got us to that round state. 

My current belief is that if each node still has its own votes then the p2p network will just end up replaying all of the votes on restart and we'll end up just fine. I couldn't get any of the tests in `replay_test.go` to fail using this change, and my additional e2e tests stop and start the whole network fine. I'm going to look into extending the WAL recovery testing to prove this change actually is safe to make.

**Comment by cason** [comment]
> I'm not sure that equivocation is the problem here--the PrivVal prevents us from double signing any vote.

It is not only equivocation, it can be for instance, amnesia. 

Recalling the example I've provided, if we see a Polka for `v` in a round `r`, we lock `v` and `r` and reject anything `!= v` in rounds `r' > r`.

If we only rely on the network for receiving messages (either old or new), we might receive a proposal for round `r' > r` while in a state where we haven't seen yet the Polka for `v` in round `r`. So we are accepting (prevoting) the new value, while we should be locked on `v` and reject anything different. This is a misbehavior that can lead to a scenario where different values are committed in different rounds.

(Actually, it is even more complex, because we only lock the value while we are in the `prevote` step of round `r`, which might not be the case when recovering, as the system has moved on to larger rounds).

**Comment by cason** [comment]
> Also, the EventDataRoundState is still being written so our Handshake should at least start from the correct place.

Can you point me out where this happens? From what I am aware, the only non-message event we log is `EndHeight`.

**Comment by ValarDragon** [comment]
Huh? How does removing votes received from gossip, from being written to WAL make sense?

Original post gives no explanation of this.

WAL replay is precisely so you can rederive your exact consensus state on crash recovery...

**Review by ValarDragon — CHANGES_REQUESTED** [review]
Huh? How does removing votes received from gossip, from being written to WAL make sense?

Original post and replies give no explanation of this.

WAL replay is precisely so you can rederive your exact consensus state on crash recovery...

**Comment by ValarDragon** [comment]
One thing you _could_ do is buffer these in RAM for one big WAL write before prevote / precommit.

**Comment by ValarDragon** [comment]
> This is true, there's no fsync for these, but we do call wal.Write which is in the critical path for receiving any message in the consensus state. And that call does buffer allocation, protobuf encoding, CRC checksums, etc., which still incurs a cost from both a time and memory perspective, so if we can agree that a change like this is safe, the data suggests that it would have meaningful benefits to Comet's performance.

The answer to me seems like its simply:
- make wal.write not expensive, none of thats fundamental. We can just change the encoding, and keep it in memory via a buffered writer until the wal.flush call

**Comment by melekes** [comment]
I really appreciate the valuable discussion on the topic! Let's continue chatting in https://github.com/cometbft/cometbft/issues/3118

Thank you all for your contributions ❤️

**Pull request closed without merging**
