### PR TITLE
Fix typo: exent -> event

### PR DESCRIPTION
**Pull request by p-offtermatt**
Closes: https://github.com/cometbft/cometbft/issues/1328

Tiny typo fix.

### CODE REVIEW

**Review by lasarojc — APPROVED** [review]
Thanks!

**Comment by thanethomson** [comment]
To which versions should this be backported?

**Review by thanethomson — APPROVED** [review]

**Comment by thanethomson** [comment]
@p-offtermatt, our usual process is to submit PRs to `main` and then backport to the relevant release branches from there. Could you please rebase this PR onto `main`? We'll make sure it gets into the relevant backport branches.

**Comment by p-offtermatt** [comment]
Not sure how to do this here because the typo is not present on main https://github.com/cometbft/cometbft/blob/2c0b09d5b675fcb1224d8b7a795f5ce724c033f2/state/txindex/indexer_service.go#L102C20-L102C20

**Comment by thanethomson** [comment]
Ah, I see. I suspect we'll need to manually backport this to `v0.34.x`.

**Comment by p-offtermatt** [comment]
Thank you!

**Pull request merged**
