### PR TITLE
docs: Sync root docs for v0.34.x with main

### PR DESCRIPTION
**Pull request by thanethomson**
Looking at https://pkg.go.dev/github.com/cometbft/cometbft, it appears as though it's rendering our readme from our v0.34.x branch.

We should sync the repo root docs with those on `main` - especially the readme. `main` should be the primary source of truth for these root docs.

---

#### PR checklist

- [x] Tests written/updated, or no tests needed
- [x] `CHANGELOG_PENDING.md` updated, or no changelog entry needed
- [x] Updated relevant documentation (`docs/`) and code comments, or no
      documentation updates needed

### CODE REVIEW

**Review by cason — APPROVED** [review]

**Comment by cason** [comment]
Consider removing/updating the following files in this branch:
 - release_notes.md
 - PHILOSOPHY.md

**Review by cason — APPROVED** [review]

**Comment by cason** [comment]
The `SECURITY.md` file in this branch hasn't been addressed by renaming yet. It has been updated in the main branch.

**Comment by thanethomson** [comment]
> The `SECURITY.md` file in this branch hasn't been addressed by renaming yet. It has been updated in the main branch.

Could you please elaborate here? I had previously sync'd the `SECURITY.md` file in this PR with `main`, and it's still in sync with `main` now.

**Comment by cason** [comment]
> > The `SECURITY.md` file in this branch hasn't been addressed by renaming yet. It has been updated in the main branch.
> 
> Could you please elaborate here? I had previously sync'd the `SECURITY.md` file in this PR with `main`, and it's still in sync with `main` now.

Sorry, I possibly considered a wrong version of the file. Now we don't have Tendermint on it.

**Pull request merged**
