### PR TITLE
refactor(internal/statesync): replace ticker with `time.After(X)`

### PR DESCRIPTION
**Pull request by hoanguyenkh**
- Remove `defer` from `ticker.Stop()` inside the loop.
- Manually call `ticker.Stop()` at necessary points in the loop to ensure tickers are stopped correctly after each iteration.

### CODE REVIEW

**Comment by faddat** [comment]
curious: how'd you identify this?

**Comment by cason** [comment]
This code doesn't make sense in general. We create a `ticker`, that is something that produces ticks every `X` time. But we only use it once. The right solution here would to use `time.After(X)`, which has some performance/GC issues...

**Comment by melekes** [comment]
> The right solution here would to use time.After(X)

@hoanguyenkh would you mind rewriting the code to use `time.After(s.retryTimeout)`?

**Comment by hoanguyenkh** [comment]
> > The right solution here would to use time.After(X)
> 
> @hoanguyenkh would you mind rewriting the code to use `time.After(s.retryTimeout)`?

thanks @melekes, @cason i rewrite this code

**Review by melekes — APPROVED** [review]
Thanks @hoanguyenkh

**Pull request merged**
