### PR TITLE
feat(libs/pubsub): allow dash symbol in event type/attribute

### LINKED ISSUE #3401: Fix querying events with dash(`-`) in their name
### Setup

**CometBFT version**: v0.38 line (tested with v0.38.7)

**Have you tried the latest version**: yes

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 22.04
- **Install tools**:
- **Others**:

**node command runtime flags**: 

### What happened?

Started a cosmos-sdk chain with sdk50 + latest cometbft on a local instance.
Tried to query events whose name contains `-` and got an error that it's invalid input. 
It was working fine in previous versions so I suspect this was introduced with the new changes in `libs/pubsub/query/syntax/scanner.go`

### What did you expect to happen?

I expect queries on events that have worked in the past to stay working

### How to reproduce it

Start a chain and try to query any event whose name contains `-`
`binary q txs --query "any-event-with-dash.failing=...."`

### Logs

failed to search for txs: error in json rpc client, with http response metadata: (Status: 200 OK, Protocol HTTP/1.1). RPC error -32603 - Internal error: offset 4: invalid input - at offset 5

### Anything else we need to know

I think this can be a quick fix but not sure if `-` is not supported on purpose for some unknown to me reason. 
Maybe add `-` as an option in `libs/pubsub/query/syntax/scanner.go` -> isTagRune()

### PR DESCRIPTION
**Pull request by melekes**
Closes #3401 

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by melekes** [comment]
cc @Lockwarr

**Review by cason — APPROVED** [review]
Looks neat, thank you for updating also the documentation.

**Comment by Lockwarr** [comment]
Just to clarify, is this going to be backported into the v0.38.x line?

**Review by hvanz — APPROVED** [review]

**Comment by melekes** [comment]
> Just to clarify, is this going to be backported into the v0.38.x line?

We are not going to backport this since we consider this a feature, not a bug. We never claimed to support the dash symbol, only `[a-zA-Z_.]`. For instance, if tomorrow someone comes and tells us they want keys to contain the $ sign, we are going to treat it as a feature too. According to our backporting policy, v0.38 and v0.37 will only backport bug fixes.

**Comment by Lockwarr** [comment]
Well, in the v0.37 line, querying `wasm-` events worked fine. I saw  there was some sort of refactoring of the way queries are scanned. 
` if tomorrow someone comes and tells us they want keys to contain the $ sign` I disagree with this. I am not trying to get a feature for a new symbol approved. I'm simply migrating our l1 and wanted to keep the functionality from previous versions. If this is not backported in v0.38, we will be blocked until the new release(v1?) as querying events is crucial part for debugging
cc @melekes @hvanz

**Comment by melekes** [comment]
@mergify backport v0.38.x

**Pull request merged**
