### PR TITLE
perf(p2p): Remove broadcast return channel

### PR DESCRIPTION
**Pull request by ValarDragon**
Remove the return channel and waitgroup from switch.Broadcast as its unused. This was costing us some CPU overhead (2% of broadcast routine as it stands right now, but broadcast routine time should be dropping) and one extra goroutine. This removes more overhead than what #3180 may introduce.

It also better highlights the point that maybe all broadcast usecases should consider using TrySend (And we potentially adapt channel buffers), ala the point in #3151 . (This would have significant system-wide impact, by significantly lowering the number of timers/scheduler overhead we have)

---

#### PR checklist

- [x] Tests written/updated - Simplifies code, the behavior being removed was never tested!
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by ValarDragon** [comment]
I recommend backporting this, as this is basically performance enhancing deadcode elimination

**Review by melekes — APPROVED** [review]
Thanks @ValarDragon ❤️

**Comment by melekes** [comment]
> I recommend backporting this, as this is basically performance enhancing deadcode elimination

It's Go API breaking.

**Comment by melekes** [comment]
@mergify backport v1.x

**Pull request merged**
