### PR TITLE
feat!: change default DB from goleveldb to pebbledb

### PR DESCRIPTION
**Pull request by melekes**
Refs #578

### CODE REVIEW

**Comment by melekes** [comment]
blocked on https://github.com/cometbft/cometbft-db/pull/202

**Comment by andynog** [comment]
I will review when cometbft-db PR mentioned above gets merged

**Comment by andynog** [comment]
@melekes noticed the tests and build were failing, tested locally and got failures too, realized that some places still used goleveldb as default. So I submitted a PR to fix those, please check if that makes sense https://github.com/cometbft/cometbft/pull/4122/commits/5c3154855809e11820cf4d32787e7e93e15f8352

**Review by andynog — APPROVED** [review]
lgtm

**Comment by melekes** [comment]
> @melekes noticed the tests and build were failing, tested locally and got failures too, realized that some places still used goleveldb as default. So I submitted a PR to fix those, please check if that makes sense [5c31548](https://github.com/cometbft/cometbft/commit/5c3154855809e11820cf4d32787e7e93e15f8352)

Thanks @andynog 👍

**Comment by melekes** [comment]
```
2024/09/21 09:50:55 [JOB 1] WAL file /tmp/-node_new_node_delete_genesis_from_db_2026691115/data/state.db/000002.log with log number 000002 stopped reading at offset: 43; replayed 1 keys in 1 batches
--- FAIL: TestNodeNewNodeDeleteGenesisFileFromDB (0.14s)
panic: pebble: closed [recovered]
	panic: pebble: closed

goroutine 179 [running]:
testing.tRunner.func1.2({0x1d7d8[20](https://github.com/cometbft/cometbft/actions/runs/10971611303/job/30466927570?pr=4122#step:6:21), 0xc000170198})
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:1635 +0x6b6
panic({0x1d7d820?, 0xc000170198?})
	/opt/hostedtoolcache/go/1.23.1/x64/src/runtime/panic.go:785 +0x132
github.com/cockroachdb/pebble.(*DB).getInternal(0xc0003fc488, {0x2be78b8, 0xa, 0xa}, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.2/db.go:537 +0x7ca
github.com/cockroachdb/pebble.(*DB).Get(...)
	/home/runner/go/pkg/mod/github.com/cockroachdb/pebble@v1.1.2/db.go:520
github.com/cometbft/cometbft-db.(*PebbleDB).Get(0xc000138098, {0x2be78b8, 0xa, 0xa})
	/home/runner/go/pkg/mod/github.com/cometbft/cometbft-db@v1.0.0/pebble.go:49 +0xb5
github.com/cometbft/cometbft/node.TestNodeNewNodeDeleteGenesisFileFromDB(0xc00032b520)
	/home/runner/work/cometbft/cometbft/node/node_test.go:544 +0x9d6
testing.tRunner(0xc00032b520, 0x1fb6160)
	/opt/hostedtoolcache/go/1.23.1/x64/src/testing/testing.go:1690 +0x[22](https://github.com/cometbft/cometbft/actions/runs/10971611303/job/30466927570?pr=4122#step:6:23)7
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.[23](https://github.com/cometbft/cometbft/actions/runs/10971611303/job/30466927570?pr=4122#step:6:24).1/x64/src/testing/testing.go:1743 +0x826
FAIL	github.com/cometbft/cometbft/node	6.155s
```

**Pull request merged**
