### PR TITLE
perf(p2p)!: Remove PeerSendBytesTotal metric

### PR DESCRIPTION
**Pull request by ValarDragon**
Component of #2840. As we discussed in the issue, we want to deprecate the peer send bytes total metric because:
- This is a costly metric (see pprof)
- This increases the cardinality of labels in Prometheus, which can slow things down in Prometheus significantly.
- Its not really useful at this level of abstraction. We don't have reported usecases of this being used yet. If we want to do it in the future, we should more likely architect it as updating a live go variable, and then sending to our metrics instance on a polling ticker (ala PeerSendQueue metric). The right levels that are interesting for outbound traffic could be the consensus gossip routines or blocksync.

To see its costly, 21% of all CPU time for live osmosis nodes in the latest Osmosis patch release is in peer.Send. over half of that time is in these metrics: 
image

Please advise for how we should go about deprecating / removing this metric? Feel free to close this PR / say you want to handle it separately.

---

#### PR checklist

- [X] Tests written/updated - N/A
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments - I didn't find any relevant docs
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by melekes — APPROVED** [review]
Thanks @ValarDragon ❤️

**Review by andynog — CHANGES_REQUESTED** [review]
Thanks, the docs need to be updated too (p2p_peer_send_bytes_total)
https://github.com/cometbft/cometbft/blob/main/docs/explanation/core/metrics.md

**Comment by andynog** [comment]
Concerning the fact that this is going to be removed and not available in the future, it would be interesting to ensure this is not used in our QA or Infra tests, I briefly looked at the logic there and couldn't find references to this particular metric, but @hvanz or @sergio-mena might have more insights. 

If we find out that some logic critically depends on this metric, probably a better approach would be to make it a configurable option if possible (e.g. disable it through a config value).

**Comment by ValarDragon** [comment]
ah thanks, didn't think to search the docs with underscores! (Explains why I didn't find it earlier haha)

**Comment by melekes** [comment]
> Thoughts on merging, and then reverting if we discover some metric consumer used this?

That's a bad dev UX 😅 

> If we find out that some logic critically depends on this metric, probably a better approach would be to make it a configurable option if possible (e.g. disable it through a config value).

please no more config options. IMO we have too many config options

**Comment by melekes** [comment]
> If we find out that some logic critically depends on this metric

Even if some external software depends on this metric, it shouldn't prevent us from removing it. CometBFT's mission and what it should do best in the world is fast and reliable consensus. And if some metric is significantly slowing CometBFT down, we should eliminate it!

**Comment by ValarDragon** [comment]
Ive tested removing it, and the prometheus time here went down ~70%! TBH that still justifies us removing the other metric or doing that more "asynchronously", e.g. via the `updateStatsRoutine`

**Comment by melekes** [comment]
@mergify backport v1.x

**Pull request merged**
