### PR TITLE
perf: improve blocksync performance

### PR DESCRIPTION
**Pull request by faddat**
Closes: #1964

This PR:

* ensures we only call validatebasic once
* continues to process blocks even if a peer sends us something that's incorrect
* makes info level logging print every 100 blocks
* ensures that debug level logging prints every block

---

#### PR checklist

- [ ] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by faddat** [comment]
Once we get #1954 merged, ci won't be a lotto.

**Review by melekes — CHANGES_REQUESTED** [review]
I don't understand how changes in this PR improve `blocksync` performance. @faddat could you please explain?

**Comment by faddat** [comment]
@melekes -- I think I made a code management mistake here, and that..... I did write such changes but they are not here.

**Comment by faddat** [comment]
(or worse, I may have actually reverted them)

**Comment by faddat** [comment]
@melekes - pretty sure that I somehow conflated this and #1977 

I think I can get it sorted tonight.

Thanks for the review!

**Comment by faddat** [comment]
closing in favor of #2016

**Pull request closed without merging**
