### PR TITLE
Upgrade to Go 1.19 on `0.34.x`

### PR DESCRIPTION
**Pull request by lasarojc**
Partially addresses #174 

The SDK uses Go 1.18 from their release that integrates with v0.34, but they should upgrade

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by julienrbrt** [comment]
Hi, we should not upgrade as it will render our point version consensus breaking due to changes in go 1.19.
Could you stay in go 1.18 on the v0.34.x line?

**Review by sergio-mena — APPROVED** [review]
Based on the latest discussion on Slack. I believe we can merge this now.

**Review by thanethomson — APPROVED** [review]
Could we please add a changelog entry and a note in our upgrading guidelines for this?

**Comment by lasarojc** [comment]
> Could we please add a changelog entry and a note in our upgrading guidelines for this?

Done!

**Pull request merged**
