### PR TITLE
feat: use go workspace

### PR DESCRIPTION
**Pull request by faddat**
This PR adds a go workspace to comet.  I noticed that the api package had diverged from main and having a go workspace is an easy way to prevent these divergences.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by faddat** [comment]
Need to fix codeql I know there's a way but I've forgotten it

**Review by melekes — APPROVED** [review]
Thanks @faddat ❤️

**Comment by melekes** [comment]
```
 2024/01/23 16:46:03 Error running go tooling: err: exit status 1: stderr: reading go.work: /home/runner/work/cometbft/cometbft/go.work:1: invalid go version '1.21.5': must match format 1.23
  
  2024/01/23 16:46:03 Extraction failed: exit status 1
  ```

**Review by adizere — APPROVED** [review]
concept ack, thanks!

**Pull request merged**
