### PR TITLE
fix TestTransportMultiplexAcceptNonBlocking

### PR DESCRIPTION
**Pull request by faddat**
This PR fixes TestTransportMultiplexAcceptNonBlocking which accounts for about 25% of "flaky test" test failures.

Please check it carefully, since there's a small amount of guesswork involved, but I do think I got it.

closes: https://github.com/cometbft/cometbft/issues/1914

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Review by melekes — APPROVED** [review]
Thanks @faddat ❤️

**Comment by faddat** [comment]
@melekes - so it seems to me that this substntially reduces failure, but doesn't stop the flakiness.

With this, and others here, I'm not 100% certain that there aren't issues in the code under test, in particular p2p code.

**Comment by faddat** [comment]
* https://github.com/cometbft/cometbft/actions/runs/7394744876/job/20116634522?pr=1954

**Comment by faddat** [comment]
Closing in favor of #1954

**Pull request closed without merging**
