### PR TITLE
test(types): fuzz ValSetVerifyCommit and ToExtendedVoteSet

### PR DESCRIPTION
**Pull request by odeke-em**
This change adds fuzzers for ValSetVerifyCommit and ToExtendedVoteSet which is a continuous effort to proactively find and fix issues in the code. These fuzzers will be added to oss-fuzz to run continuously.

### CODE REVIEW

**Comment by faddat** [comment]
fuzz is good :)

**Comment by adizere** [comment]
Is it feasible to fix the linting CI failure? https://github.com/cometbft/cometbft/actions/runs/7500889624/job/20420464941?pr=2011#step:5:12780

**Comment by faddat** [comment]
* https://github.com/orijtech/cometbft/pull/1

**Comment by odeke-em** [comment]
Thanks for @faddat for the PR, but instead of modifying things more, I just added `//nolint:musttag`. @adizere thanks for the ping, the lint failures have all been fixed and everything should now be passing.

**Review by melekes — COMMENTED** [review]
Thanks @odeke-em ❤️

**Comment by melekes** [comment]
It would be nice to include scripts used to generate the test data. That way, if data structures change, we will have a way to update the test fixtures.

**Comment by melekes** [comment]
Closing as stale. @odeke-em please let me know if you still want to work on this 🙏

**Pull request closed without merging**
