### PR TITLE
refactor: improve debug information in HTTP handler logging

### PR DESCRIPTION
**Pull request by mmsqe**
Updates: https://github.com/cometbft/cometbft/issues/1505

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by melekes — APPROVED** [review]
Thanks @mmsqe ❤️

**Comment by melekes** [comment]
I don't think the PR addresses https://github.com/cometbft/cometbft/issues/1505 because `logger.Debug` doesn't return an error.

**Comment by mmsqe** [comment]
> I don't think the PR addresses #1505 because `logger.Debug` doesn't return an error.

You're right, this change is mainly for the log instead of abci_query data part.

**Review by sergio-mena — APPROVED** [review]
Thanks for this @mmsqe , please update the PRs title to better reflect what the PR is achieving (improving debug information)

**Pull request merged**
