### PR TITLE
ADR 103 Local State Sync Support (ported from Tendermint Core repo)

### LINKED ISSUE #28: State sync from local snapshot: Understand problem, explore solutions
Tasks:

- [x] Analyze and understand the problem ADR083 is trying to address
- [x] Gauge users' interest in solving this problem (how painful it is _not_ to solve it?)
- [x] Explore all possible solutions, among them ADR083 (tendermint/tendermint#9651)
- [x] Adapt ADR083 according to the solution decided, finalize and merge it

DoD:
- We have made sure that users want the problem solved
- We have decided on a solution, and implemented it
- The ADR is merged

Original issue: tendermint/tendermint#9947

### PR DESCRIPTION
**Pull request by adizere**
Closes #28 

[Rendered view of adr-103-local-state-sync.md](https://github.com/cometbft/cometbft/blob/adi/28_local_sync_adr/docs/architecture/adr-103-local-state-sync.md)

TODOs

- [ ] Cross-validate with the solution in #728 
- [ ] Update docs to reflect the new workflow, with instructions on how users can do local (out-of-band) state sync
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by chillyvee** [comment]
Thank you for the notes.  Due to the many possible solutions this PR has been rewritten a number of times. '
1) Should we hold until more architectural decisions are made?
2) Can decide whether we are targeting v0.34 or main?

**Comment by adizere** [comment]
Thanks for the quick feedback!

> If you think reviewing a working implementation for Juno v14 is helpful, we can update all the code. But it won't be possible to target main since Juno still targets v0.34
> Can decide whether we are targeting v0.34 or main?

It would be helpful to have instructions on how to use the solution in #728 in Juno (or other live network). Thanks in advance for that! I think targeting v0.34 should be fine.

**Comment by cason** [comment]
So, for context see: https://github.com/cometbft/cometbft/issues/28#issuecomment-1536019083

**Comment by adizere** [comment]
Superseded by #801

**Pull request closed without merging**
