### PR TITLE
feat: do not start indexer service (back port: #3331)

### PR DESCRIPTION
**Pull request by mmsqe**
if block && tx indexers are no-op

---

- [ ] ~~Tests written/updated~~
- [ ] ~~Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by melekes** [comment]
The PR breaks the Go API, so we can't backport it. However, we can backport it to the `v0.38-experimental` branch if you want.

**Comment by mmsqe** [comment]
> The PR breaks the Go API, so we can't backport it. However, we can backport it to the `v0.38-experimental` branch if you want.

Got it thanks, not sure if can add extra `IndexerFromConfigWithDisabledIndexers` without changing exist one?

**Comment by melekes** [comment]
> > The PR breaks the Go API, so we can't backport it. However, we can backport it to the `v0.38-experimental` branch if you want.
> 
> @melekes Got it thanks, not sure if can add extra [IndexerFromConfigWithDisabledIndexers](https://github.com/mmsqe/cometbft/commit/f173110596d6eb7a9f4f5faba2d21590d9b2bf88) without changing exist one?

Yes we can!

**Review by melekes — APPROVED** [review]
👍

**Pull request merged**
