### PR TITLE
v0.38-experimental: Add CAT mempool support

### PR DESCRIPTION
**Pull request by adizere**
This is a port of the first commit from Hernan's work from branch `experimental/cat` onto v0.38-exp line. Specifically, I used the following command:

	git rebase --onto experimental/cat/0.38 0fa29a58ee82b81ffb735f9b296eb451a36c1e6d 094c67101a55acc4bf931cdacb4cc8576aa7fc47

Where:
- experimental/cat/0.38 is a new branch based on v0.38.x-experimental
- 094c67101a55acc4bf931cdacb4cc8576aa7fc47 is the first commit in Hernan's branch
- 0fa29a58ee82b81ffb735f9b296eb451a36c1e6d is the parent of the first commit.

Next steps:
1. Fix mockery & tests
2. Continue porting the other commits from Hernan's branch.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by faddat** [comment]
I think that this is one of two viable paths for "future of the mempool".

The other viable path is "no mempool".

To develop "no mempool" I think we should try to find a chain actively using comet that wants this feature, that way it will be easiest to support (I envision "no mempool" as something that we drop in)

**Comment by faddat** [comment]
as far as I can tell, this is quite important

**Comment by faddat** [comment]
Hey Adi, I am going through this PR, and I want to see if I can summarize the changes and issues:

* there were a few unresolved merge conflicts -- I've resolved them favoring the incoming code.
* we're now passing only the transaction into checktx

There are some others of course, but these seem like the ones that are causing issues.

**Comment by adizere** [comment]
ref: #2027 deprioritized for the moment

**Pull request closed without merging**
