### PR TITLE
chore: remove amazon linux Dockerfile and update test/docker/Dockerfile

### PR DESCRIPTION
**Pull request by faddat**
* amazon linux Dockerfile is configured for go v1.12.x -- it is clearly unused
* tests Dockerfile is configured for go v1.15.x -- it's clearly unused

The presence of these files is a bug/technical debt or such.  They make the code harder to read and understand and create the impression that they may serve a purpose.

closes: #2134 

---

#### PR checklist

- [ ] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by melekes — APPROVED** [review]
👍

**Review by andynog — CHANGES_REQUESTED** [review]
Should the `Makefile` in the root of the repo also be updated ? I see this entry there 

```
build_c-amazonlinux:
	$(MAKE) -C ./DOCKER build_amazonlinux_buildimage
	docker run --rm -it -v `pwd`:/cometbft cometbft/cometbft:build_c-amazonlinux
.PHONY: build_c-amazonlinux
```

**Comment by faddat** [comment]
Nice catch @andynog -- I'll address that now

**Comment by faddat** [comment]
@andynog I just reviewed the Pr and I do believe that it updates the make file as well.

**Comment by faddat** [comment]
ah :).  Also that one lol :)

**Comment by melekes** [comment]
`test/docker/Dockerfile` is used by `test_integrations` cmd, which I'm not sure we use anymore. So we should remove it along with any sub-commands it calls.

**Comment by faddat** [comment]
Makes sense to me. I'll have a look.

**Comment by faddat** [comment]
@melekes -- the Dockerfile was broken anyhow, as it tried to build `make tools` which no longer exists.  

I think it might make sense to put the rest of this into an issue, unless you think it is alright to change the e2e image to include a folder, let's call it `/testnet` in which case I think that we could make this a part of the e2e image.  

So, now instead of removing this extra Dockerfile, it's fixed, so that when we next make a release, that process will go smoothly.

**Review by melekes — APPROVED** [review]
👍

**Pull request merged**
