### PR TITLE
abci++ tutorial

### PR DESCRIPTION
**Pull request by samricotta**
ABCI++ tutorial that was worked on last year by Callum and I. It still needs a little bit of clean up but its about 90% there, just needs a little TLC on the tests and on documentation side of things.

I dont have the time to do the cleanup myself but please let me know if you need anything.

---

#### PR checklist

- [x] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by samricotta** [comment]
@alijnmerchant21 here it is 👍

**Comment by adizere** [comment]
This is amazing, thanks @samricotta !

**Comment by alijnmerchant21** [comment]
Thank you @samricotta for making this PR. I'll review it & clean up documentation, test, etc.

**Comment by sergio-mena** [comment]
Thanks a lot @samricotta for sharing this with us!

**Comment by adizere** [comment]
I suspect this will be superseded by the work in branch https://github.com/cometbft/cometbft/tree/abci-tutorial/docs/guides/abci/forum-application. Closing for the moment, @alijnmerchant21 correct me if I'm wrong.

Thanks Sam for kicking off the tutorial, I think we reused a big chunk of your original idea, much appreciated!

**Pull request closed without merging**
