### PR TITLE
docs(api): Added basic readme for /api directory

### PR DESCRIPTION
**Pull request by adizere**
---

#### PR checklist

- [ ] ~~Tests written/updated~~
- [ ] ~~Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~
- [X] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [X] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by cason — APPROVED** [review]
Are we still using the `tendermint` registry, even from v1? If we are not, we should update `../proto/README.md`. 

You could take the opportunity to update `go.sum` here with `go mod tidy`.

**Comment by adizere** [comment]
> Are we still using the tendermint registry, even from v1? If we are not, we should update ../proto/README.md.

Can you explain more what exactly to update? I had a look over the readme and was not clear what to update.

> You could take the opportunity to update go.sum here with go mod tidy.

Good point, thanks for pointing out! 7f9431473

**Review by melekes — APPROVED** [review]
👍

**Comment by cason** [comment]
The link is to the tendermint registry: https://github.com/cometbft/cometbft/blob/main/proto/README.md?plain=1#L76

But we have a Comet registry: https://buf.build/cometbft/cometbft

Anyway, this shouldn't be part of this PR.

**Pull request merged**
