### PR TITLE
bring cat mempool to parity with main

### PR DESCRIPTION
**Pull request by faddat**
## Cat Mempool

Note: 100% of the code work was done by @hvanz.

I just think that we should try to get this over the line because there are serious mempool issues that are resolved by CAT and that in the end, it is likely that Comet will feature a BOOL as to weather or not to have a mempool and that CAT will be the default one.

Thanks to Celestia for implementing the original!

### Note

This kicked off a pretty complex merge.  I think that all that is left here is to take proto changes from v1beta1 and apply them to v1.  Please feel free to fork, remix, toss, etc.

---------------

- Add CAT mempool reactor
- Add missing changes to rpc/core/mempool.go
- e2e: Add MempoolReactor to manifest
- + update cat reactor following merge
- Fix lint
- Revert to fix lint
- More fixes
- make proto-gen
- Add SyncReactor interface
- Refactor MempoolTx into CListEntry to fix lint
- Add IsEmpty method to CListEntry
- Increase defaultGossipDelay and remove jitter
- e2e: Add pex_reactor and log_level to manifest
- Rename (mempool_)reactor to gossip_protocol
- document the cat mempool

### CODE REVIEW

**Comment by faddat** [comment]
note: I'm currently doing the merge conflict, it's pretty tough.

**Comment by cason** [comment]
> note: I'm currently doing the merge conflict, it's pretty tough.

Maybe you should consider waiting for Hernán to come back, next week. He is the one with context on this matter.

**Comment by faddat** [comment]
I'll give it a go.  Nearly complete I think.

**Comment by faddat** [comment]
I think we just need to apply the proto changes that @hvanz made to v1 and good to go.

**Comment by faddat** [comment]
Only thing remaining is e2e but not totally sure what to do about that.

**Comment by adizere** [comment]
We just had a chat with Celestia team. It doesn't seem like they need this right now since they are not seeing bandwidth limits get hit. 

We plan to test CAT in Q2, unless a specific user needs it. Do you know of an app-chain team needing CAT mempool @faddat ?

**Comment by faddat** [comment]
Given the update from the original author, it makes perfect sense to close this.

Happy new year!

**Pull request closed without merging**
