### PR TITLE
feat(blocksync): sort peers by download rate & multiple requests for closer blocks

### LINKED ISSUE #2379: blocksync: bandwidth / block download improv ideas
@ValarDragon:

- [ ]  If we are approaching a block (e.g., < 25 away), and our current peer we've asked is slow, try asking from more peers, as this will become the bottleneck
- [ ] Somehow track which peers are better at serving blocks to get more from them. (We see direct peering to one peer causing significant gains / removing the bandwidth bottleneck at current state machine processing times on Osmosis. We are aiming to get this processing time 5x improved)
- [ ] Tighten the timeouts / see if we are doing more timeouts than we need

### PR DESCRIPTION
**Pull request by melekes**
It can be reviewed commit by commit.

1. Request the block N from peer B immediately after getting `NoBlockResponse` from peer A https://github.com/cometbft/cometbft/pull/2475/commits/a718fb47913d58322e0af27167c76f5a2978be20
2. Sort peers by download rate (the fastest peer is picked first) https://github.com/cometbft/cometbft/pull/2475/commits/cf19851c7b51510e3b406c151139d40ad2e02a66
3. Request a block from peer B if we are approaching pool's height (less than 50 blocks) and the current peer A is slow in sending us the block https://github.com/cometbft/cometbft/pull/2475/commits/e06ebfe60bc162b8def8d0958a098b9d45a860f7 https://github.com/cometbft/cometbft/pull/2475/commits/e97007fd691fde41b2f362703ebe03607025fbc8

Closes #2379 

### Benchmarks

Osmosis:

without this PR (baseline): 11.45m
with this PR: 7.29m
~ 36% decrease

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by melekes** [comment]
Since it's API breaking, this PR won't be backported to v0.38. But a subset of changes could be backported if needed.

**Review by andynog — APPROVED** [review]
I'm not super familiar with the blocksync logic but went through the code and these changes looks fine to me.

**Review by czarcas7ic — APPROVED** [review]
I am still getting the non deterministic test failure seen here https://github.com/osmosis-labs/cometbft/actions/runs/8180402720/job/22368625848?pr=16

But other than this I have tested this over 30+ times across ~1.5k blocks each time and have had great results.

**Comment by melekes** [comment]
@czarcas7ic you need to pull the latest changes. I've fixed the DATA RACE there.

**Pull request merged**
