### PR TITLE
chore(state): `v1LegacyLayout` keys no longer use `fmt.Sprintf()`.

### PR DESCRIPTION
**Pull request by alesforz**
The `v1LegacyLayout` type uses `fmt.Sprintf()` to create the DB keys. This PR substitutes `fmt.Sprintf` with string concatenation, which is 3-4 times faster for such a simple string.

In general, we shouldn't use `fmt.Sprintf()` to concatenate strings, because it's inefficient. 
Exceptions could be constructing error messages (but we should use `fmt.Errorf()` for that) or tests.

---

#### PR checklist

- ~[ ] Tests written/updated~
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- ~[ ] Updated relevant documentation (`docs/` or `spec/`) and code comments~

### CODE REVIEW

**Review by melekes — APPROVED** [review]
👍

**Comment by jmalicevic** [comment]
Maybe you can do the same for the blockStore? https://github.com/cometbft/cometbft/blob/alesforz/v1keylayout-sprintf/store/db_key_layout.go

**Comment by alesforz** [comment]
> Maybe you can do the same for the blockStore? https://github.com/cometbft/cometbft/blob/alesforz/v1keylayout-sprintf/store/db_key_layout.go

Will do this in a separate PR 👍

**Comment by alesforz** [comment]
**Note**: the changes in this PR are superseded by #4490.

**Pull request merged**
