### PR TITLE
Backports #1558 and #1584 to 0.38.x

### PR DESCRIPTION
**Pull request by lasarojc**
See #1558 and #1584

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by lasarojc** [comment]
Blocked by #1589

**Review by melekes — APPROVED** [review]
👍

**Comment by jmalicevic** [comment]
For the experimental branch, would it not be easier to backport to 0.38 and then merge 0.38 into experimental? Probably depends on how we want to treat the experimental branch.

**Comment by lasarojc** [comment]
> For the experimental branch, would it not be easier to backport to 0.38 and then merge 0.38 into experimental? Probably depends on how we want to treat the experimental branch.

Done. The PR has now been rebased to v0.38.x instead of experimental.

**Pull request merged**
