### PR TITLE
feat(crypto)!: remove PubKey#Equals and PrivKey#Equals

### PR DESCRIPTION
**Pull request by melekes**
a) it's unused
b) Cosmos SDK folks suggested to remove it in one of the issues 

Refs https://github.com/cometbft/cometbft/issues/2426

---

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by tac0turtle — APPROVED** [review]
thank you

**Comment by cason** [comment]
I think it is related to https://github.com/cometbft/cometbft/issues/2426.

**Review by cason — APPROVED** [review]
+1

**Comment by adizere** [comment]
Copying @raynaudoe @jleni

**Pull request merged**
