### PR TITLE
fix(grpc): implemented missing optional function for BlocksResultsService in gRPC client (backport #3693)

### LINKED ISSUE #3692: fix(grpc): Add enabling functional options for `BlocksResultsService`
Reposting from [this](https://github.com/cometbft/cometbft/issues/3635#issuecomment-2276280362_) discussion.

### The Problem
The list of option functions [here](https://github.com/cometbft/cometbft/blob/3b80085c35864f851b0c5034b4391aab2e059517/rpc/grpc/client/client.go#L69) doesn't have `WithBlockResultsService(...)`, yet [below](https://github.com/cometbft/cometbft/blob/3b80085c35864f851b0c5034b4391aab2e059517/rpc/grpc/client/client.go#L147) we check if the service is enabled (I suppose it will never be if that function isn't present and called).

We need to implement `WithBlockResultsService(...)`.

### PR DESCRIPTION
**Pull request by alesforz**
Closes #3692.

---

#### PR checklist

~- [ ] Tests written/updated~
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

(cherry picked from commit 9cb427c8d7fce7b7d86ad6d09b5c681a3aefd174)

---

#### PR checklist

~- [ ] Tests written/updated~
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Review by andynog — COMMENTED** [review]
There are many changes to this PR that are un-related to just adding the missing optional function. Is there a reason for all these changes to be included in this PR ?

**Comment by melekes** [comment]
> The docker compose changes were also a problem on the other branches. See https://github.com/actions/runner-images/issues/10384. We merged a https://github.com/cometbft/cometbft/pull/3614 to do the changes I made here manually. Without the change to docker compose in the relevant files, the test would fail.

Can't we merge `v0.38.x` into this branch? Then we will have the latest changes, no?

**Comment by melekes** [comment]
I agree with @andynog here. I believe if we first merge `v0.38.x` here, we will have fewer merge conflicts, and history will look better.

**Comment by andynog** [comment]
> I agree with @andynog here. I believe if we first merge `v0.38.x` here, we will have fewer merge conflicts, and history will look better.

Yes I think the first thing would be to catch up with v0.38 that is overdue, then automate this to always keep it in sync with v0.38, then backport to experimental will be much simpler and straightforward

**Comment by alesforz** [comment]
so, if I understand your proposal, I'll first revert the last 2 commits of this PR, then merge branch `v0.38.x` into this branch.
Is this what you mean? Or should we merge `v038.x` in a different PR to handle possible merge conflicts?

**Review by melekes — APPROVED** [review]

**Comment by melekes** [comment]
```
--- FAIL: TestProvider (19.54s)
    http_test.go:63: 
        	Error Trace:	/home/runner/work/cometbft/cometbft/light/provider/http/http_test.go:63
        	Error:      	Should be true
        	Test:       	TestProvider
    http_test.go:78: 
        	Error Trace:	/home/runner/work/cometbft/cometbft/light/provider/http/http_test.go:78
        	Error:      	Not equal: 
        	            	expected: &errors.errorString{s:"height requested is too high"}
        	            	actual  : &errors.errorString{s:"light block not found"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,3 @@
        	            	 (*errors.errorString)({
        	            	- s: (string) (len=28) "height requested is too high"
        	            	+ s: (string) (len=21) "light block not found"
        	            	 })
```

**Pull request merged**
