### PR TITLE
build(deps): Bump minimum Go version to v1.23

### LINKED ISSUE #4039: GO-2024-3107
https://pkg.go.dev/vuln/GO-2024-3107

Vulnerable versions: before go1.22.7, from go1.23.0-0 before go1.23.1

```
Vulnerability #1: GO-2024-3107
    Stack exhaustion in Parse in go/build/constraint
  More info: https://pkg.go.dev/vuln/GO-2024-3107
  Standard library
    Found in: go/build/constraint@go1.22.5
    Fixed in: go/build/constraint@go1.22.7
    Example traces found:
Error:       #1: scripts/metricsgen/metricsgen.go:158:27: metricsgen.ParseMetricsDir calls parser.ParseDir, which eventually calls constraint.Parse

Vulnerability #2: GO-[20](https://github.com/cometbft/cometbft/actions/runs/10766490607/job/29852325945?pr=4025#step:6:21)24-3106
    Stack exhaustion in Decoder.Decode in encoding/gob
  More info: https://pkg.go.dev/vuln/GO-2024-3106
  Standard library
    Found in: encoding/gob@go1.[22](https://github.com/cometbft/cometbft/actions/runs/10766490607/job/29852325945?pr=4025#step:6:23).5
    Fixed in: encoding/gob@go1.22.7
    Example traces found:
Error:       #1: rpc/jsonrpc/server/http_server.go:262:15: server.defaultHandler.ServeHTTP calls http.ServeMux.ServeHTTP, which eventually calls gob.Decoder.Decode

Vulnerability #3: GO-20[24](https://github.com/cometbft/cometbft/actions/runs/10766490607/job/29852325945?pr=4025#step:6:25)-3105
    Stack exhaustion in all Parse functions in go/parser
  More info: https://pkg.go.dev/vuln/GO-2024-3105
  Standard library
    Found in: go/parser@go1.22.5
    Fixed in: go/parser@go1.22.7
    Example traces found:
Error:       #1: scripts/metricsgen/metricsgen.go:158:[27](https://github.com/cometbft/cometbft/actions/runs/10766490607/job/29852325945?pr=4025#step:6:28): metricsgen.ParseMetricsDir calls parser.ParseDir
Error:       #2: scripts/metricsgen/metricsgen.go:204:24: metricsgen.GenerateMetricsFile calls format.Source, which eventually calls parser.ParseFile
```

### PR DESCRIPTION
**Pull request by melekes**
Closes #4039 

cometbft-db PR: https://github.com/cometbft/cometbft-db/pull/194

---

#### PR checklist

- [ ] ~~Tests written/updated~~
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [x] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by cason** [comment]
This error is also new:

```
panic: test timed out after 6m40s
	running tests:
		TestBroadcastEvidence_DuplicateVoteEvidence (6m40s)
```

And it also fails locally.

**Comment by cason** [comment]
Another new test failure:

```
FAIL	github.com/cometbft/cometbft/light	460.023s
CometBFT running!
coverage: 65.7% of statements
panic: test timed out after 6m40s
	running tests:
		TestProvider (6m40s)
```

Also fails locally.

**Comment by melekes** [comment]
```
==================
WARNING: DATA RACE
Write at 0x00c000396570 by goroutine 25:
  github.com/cometbft/cometbft/internal/autofile.(*Group).RotateFile()
      /Users/antonk/work/informal/cometbft/internal/autofile/group.go:317 +0x214
  github.com/cometbft/cometbft/internal/autofile.(*Group).checkHeadSizeLimit()
      /Users/antonk/work/informal/cometbft/internal/autofile/group.go:255 +0x78
  github.com/cometbft/cometbft/internal/autofile.(*Group).processTicks()
      /Users/antonk/work/informal/cometbft/internal/autofile/group.go:235 +0xa0
  github.com/cometbft/cometbft/internal/autofile.(*Group).OnStart.gowrap1()
      /Users/antonk/work/informal/cometbft/internal/autofile/group.go:141 +0x34

Previous read at 0x00c000396570 by goroutine 20:
  github.com/cometbft/cometbft/internal/autofile.(*Group).MaxIndex()
      /Users/antonk/work/informal/cometbft/internal/autofile/group.go:184 +0x84
  github.com/cometbft/cometbft/internal/consensus.(*BaseWAL).SearchForEndHeight()
      /Users/antonk/work/informal/cometbft/internal/consensus/wal.go:244 +0x30
  github.com/cometbft/cometbft/internal/consensus.TestWALTruncate()
      /Users/antonk/work/informal/cometbft/internal/consensus/wal_test.go:76 +0x414
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:657 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).checkAndCleanFiles()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_util.go:52 +0x1d0
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:136 +0x674
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x1ec
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:657 +0x138
  fmt.(*ss).doScanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:1230 +0x328
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:482 +0x84
  github.com/syndtr/goleveldb/leveldb.openDB()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:131 +0x668
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:203 +0x274
  fmt.Fscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:143 +0x94
  fmt.Sscanf()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/fmt/scan.go:114 +0x130
  github.com/syndtr/goleveldb/leveldb/storage.fsParseName()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:643 +0x74
  github.com/syndtr/goleveldb/leveldb/storage.(*fileStorage).List()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/storage/file_storage.go:458 +0x364
  github.com/syndtr/goleveldb/leveldb.(*session).recover.func1()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:134 +0xb4
  runtime.deferreturn()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:605 +0x5c
  github.com/syndtr/goleveldb/leveldb.Open()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:189 +0xb0
  github.com/syndtr/goleveldb/leveldb.OpenFile()
      /Users/antonk/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:225 +0x6c
  github.com/cometbft/cometbft-db.NewGoLevelDBWithOpts()
      /Users/antonk/go/pkg/mod/github.com/cometbft/cometbft-db@v0.15.0/goleveldb.go:32 +0xa8
  github.com/cometbft/cometbft-db.NewGoLevelDB()
      /Users/antonk/go/pkg/mod/github.com/cometbft/cometbft-db@v0.15.0/goleveldb.go:27 +0x48
  github.com/cometbft/cometbft/abci/example/kvstore.NewPersistentApplication()
      /Users/antonk/work/informal/cometbft/abci/example/kvstore/kvstore.go:65 +0x2c
  github.com/cometbft/cometbft/internal/consensus.WALGenerateNBlocks()
      /Users/antonk/work/informal/cometbft/internal/consensus/wal_generator.go:34 +0xfc
  github.com/cometbft/cometbft/internal/consensus.TestWALTruncate()
      /Users/antonk/work/informal/cometbft/internal/consensus/wal_test.go:66 +0x350
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1690 +0x184
  testing.(*T).Run.gowrap1()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1743 +0x40

Goroutine 25 (running) created at:
  github.com/cometbft/cometbft/internal/autofile.(*Group).OnStart()
      /Users/antonk/work/informal/cometbft/internal/autofile/group.go:141 +0xe8
  github.com/cometbft/cometbft/libs/service.(*BaseService).Start()
      /Users/antonk/work/informal/cometbft/libs/service/service.go:146 +0x4a8
  github.com/cometbft/cometbft/internal/consensus.(*BaseWAL).OnStart()
      /Users/antonk/work/informal/cometbft/internal/consensus/wal.go:134 +0xa4
  github.com/cometbft/cometbft/libs/service.(*BaseService).Start()
      /Users/antonk/work/informal/cometbft/libs/service/service.go:146 +0x4a8
  github.com/cometbft/cometbft/internal/consensus.TestWALTruncate()
      /Users/antonk/work/informal/cometbft/internal/consensus/wal_test.go:52 +0x2a0
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1690 +0x184
  testing.(*T).Run.gowrap1()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1743 +0x40

Goroutine 20 (running) created at:
  testing.(*T).Run()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1743 +0x5e0
  testing.runTests.func1()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:2168 +0x80
  testing.tRunner()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1690 +0x184
  testing.runTests()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:2166 +0x6e0
  testing.(*M).Run()
      /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:2034 +0xb74
  github.com/cometbft/cometbft/internal/consensus.TestMain()
      /Users/antonk/work/informal/cometbft/internal/consensus/replay_test.go:44 +0x168
  main.main()
      _testmain.go:259 +0x114
==================

```

**Review by andynog — APPROVED** [review]
lgtm, thanks @melekes

**Pull request merged**
