### PR TITLE
e2e: Add `load_max_txs` option to manifest

### PR DESCRIPTION
**Pull request by hvanz**
An option to set a limit to the number of transactions generated by the `load` command of the e2e framework.

---

#### PR checklist

- [ ] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Review by melekes — APPROVED** [review]
👍

**Comment by hvanz** [comment]
@Mergifyio backport v1.0.x

**Comment by hvanz** [comment]
https://github.com/Mergifyio backport v1.x

**Comment by hvanz** [comment]
https://github.com/Mergifyio backport v0.38.x

**Comment by melekes** [comment]
https://github.com/Mergifyio backport v0.34.x

**Pull request merged**
