### PR TITLE
feat(crypto/merkle): add test for `proof_op.go`

### PR DESCRIPTION
**Pull request by sherry-landy**

### CODE REVIEW

**Comment by sherry-landy** [comment]
test result is shown:
image

**Review by melekes — APPROVED** [review]
Thanks @sherry-landy 👍

**Comment by melekes** [comment]
```
FAIL	github.com/cometbft/cometbft/crypto/merkle [setup failed]
package github.com/cometbft/cometbft/crypto/merkle
	imports github.com/cometbft/cometbft/crypto/merkle: import cycle not allowed in test
```

**Comment by melekes** [comment]
```
golangci-lint-full.......................................................Failed
- hook id: golangci-lint-full
- files were modified by this hook

WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.

gofumpt..................................................................Passed
codespell................................................................Passed
pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
All changes made by hooks:
diff --git a/crypto/merkle/proof_op_test.go b/crypto/merkle/proof_op_test.go
index c704780..4a4df34 100644
--- a/crypto/merkle/proof_op_test.go
+++ b/crypto/merkle/proof_op_test.go
@@ -4,9 +4,10 @@ import (
 	"errors"
 	"testing"
 
+	"github.com/stretchr/testify/require"
+
 	cmtcrypto "github.com/cometbft/cometbft/api/cometbft/crypto/v1"
 	"github.com/cometbft/cometbft/crypto/merkle"
-	"github.com/stretchr/testify/require"
 )
 
 type MockProofOperator struct {
```

@sherry-landy do you mind moving the import as per ^? or running `make pre-commit && pre-commit run --all-files`?

**Comment by sherry-landy** [comment]
ok, the code has been formated. @melekes

**Pull request merged**
