### PR TITLE
test(e2e): add storage test

### PR DESCRIPTION
**Pull request by andynog**
Re-add the `storage.toml` e2e test.

context: this test was added over by mistake `simple.toml`. Simple was restored here https://github.com/cometbft/cometbft/pull/3181

The Storage test is failing, so opening this PR for now as draft until test is not failing. Once tests run without errors, will make it ready for review.

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by sergio-mena** [comment]
@andynog shall we reopen this?

**Comment by sergio-mena** [comment]
@andynog 🙏

**Comment by andynog** [comment]
now that the nightly tests are passing again, will try to merge this back

**Review by melekes — APPROVED** [review]
👍

**Pull request closed without merging**
