### PR TITLE
v0.38.x-experimental: Backport e2e flakiness fix

### PR DESCRIPTION
**Pull request by jmalicevic**
Manual backport of #1467

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments

### CODE REVIEW

**Comment by cason** [comment]
So we are just skipping the tests when data companion is running?

**Comment by jmalicevic** [comment]
Yes for the moment, we might figure out a better way to test this meaningfully, but right now there is no way to make the tests deterministic.

**Comment by sergio-mena** [comment]
@jmalicevic Is there an issue so we don't forget to do this?
e2e tests are the best thing we have to catch problems ATM, so I think it is important that they test a newly shipped feature such as the new pruning mechanism

**Comment by jmalicevic** [comment]
The pruning mechanism is tested but it should not be tested here. The functionality of this test is to verify that a node has the same blocks as an archive node. Which is not really deterministically possible atm when pruning happens ad-hoc. 

I am however working on reducing the flakiness of the gRPC tests which suffer from the same problem and the solution for that might be appicable here as well. #1470

**Review by sergio-mena — APPROVED** [review]

**Review by thanethomson — APPROVED** [review]

**Pull request merged**
