### PR TITLE
chore(tests): uncomment mempool & p2p reactor tests

### LINKED ISSUE #3689: fix TestMempoolReactorSendLaggingPeer & TestConnectionSpeedForPeerReceivedFromSeed
The tests were commented out in https://github.com/cometbft/cometbft/pull/3686 due to constant failures.

### PR DESCRIPTION
**Pull request by melekes**
Closes #3689 

---

#### PR checklist

- [x] Tests written/updated
- [ ] ~~Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)~~
- [ ] ~~Updated relevant documentation (`docs/` or `spec/`) and code comments~~
- [x] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by melekes** [comment]
```
--- FAIL: TestReactorBroadcastTxsMessage (120.06s)
    reactor_test.go:62: Timed out waiting for txs
--- FAIL: TestMempoolReactorSendLaggingPeer (120.79s)
    reactor_test.go:187: Timed out waiting for txs
FAIL
coverage: 81.4% of statements
FAIL	github.com/cometbft/cometbft/mempool	267.852s
ok  	github.com/cometbft/cometbft/node	6.962s	coverage: 60.2% of statements
ok  	github.com/cometbft/cometbft/p2p	9.941s	coverage: 69.0% of statements
ok  	github.com/cometbft/cometbft/p2p/conn	6.932s	coverage: 84.2% of statements
--- FAIL: TestConnectionSpeedForPeerReceivedFromSeed (0.04s)
    pex_reactor_test.go:312: 
        	Error Trace:	/home/runner/work/cometbft/cometbft/p2p/pex/pex_reactor_test.go:312
        	Error:      	Should be zero, but was 1
        	Test:       	TestConnectionSpeedForPeerReceivedFromSeed
FAIL
```

**Review by sergio-mena — APPROVED** [review]
Thanks a lot for this 🙏.
I see you're just uncommenting them, so what caused them to be commented out in the first place (or am I missing some further change in this PR?)

**Comment by melekes** [comment]
> Thanks a lot for this 🙏. I see you're just uncommenting them, so what caused them to be commented out in the first place (or am I missing some further change in this PR?)

Constant failures. The mempool tests probably fail because of [#3694](https://github.com/cometbft/cometbft/issues/3694). This issue may be fixed by [#3700](https://github.com/cometbft/cometbft/pull/3700).

**Review by andynog — APPROVED** [review]
Lgtm, thanks!

**Comment by melekes** [comment]
```
--- FAIL: TestReactorBroadcastTxsMessage (120.19s)
    reactor_test.go:62: Timed out waiting for txs
--- FAIL: TestMempoolReactorSendLaggingPeer (124.57s)
    reactor_test.go:187: Timed out waiting for txs
coverage: 82.0% of statements
panic: test timed out after 6m40s
running tests:
	TestMempoolReactorMaxActiveOutboundConnections (2m[18](https://github.com/cometbft/cometbft/actions/runs/10382617814/job/28761983651?pr=3698#step:6:19)s)
```

https://github.com/cometbft/cometbft/actions/runs/10382617814/job/28761983651?pr=3698

**Comment by hvanz** [comment]
This PR should be merged after #3700, which fixes the tests.

**Pull request merged**
