### PR TITLE
feat(crypto): Upgrade all usage of `crypto/sha256` to `minio/sha256-simd`

### PR DESCRIPTION
**Pull request by itsdevbear**
Free performance boost, used in hundreds of production projects.

---

#### PR checklist

- [ ] Tests written/updated
- [ ] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [ ] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [ ] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

### CODE REVIEW

**Comment by itsdevbear** [comment]
Will be CPU architecture dependant, ensure test environment is setup correctly

**Comment by andynog** [comment]
Thanks @itsdevbear. 

@sergio-mena do you know if we have a mixed environment in our tests ? Do we test on Intel and ARM ? 

Looks like the benefits are dependent on message size according to the repo. Might be also interesting to see if this could be tested with different input sizes.

**Comment by andynog** [comment]
One concern that I have though is that this library seems to be a bit stale, [last commit](https://github.com/minio/sha256-simd/commits/master/) was February 2023. Maybe it's stable enough. But since we're replacing it everywhere where a Sha256 is needed, changing it on hash, merkletree, keys, etc, 

It is critical that this library is vetted. I understand this is used in production in many projects, but the concern is if there's a vulnerability how fast it can be addressed as opposed to using the official one that would be patched possibly faster.

**Comment by sergio-mena** [comment]
We are in the process of having a golang crypt expert vet this library change.

**Comment by itsdevbear** [comment]
I can also hide behind an optional build flag is desired.

**Comment by itsdevbear** [comment]
@andynog yeah intel and arm, but notably will see the greatest improvement on cpus with AVX-512 support

**Comment by itsdevbear** [comment]
This being said, we want to optimize some places in the code to use the AVX-512 scheduler directly. But that's a bigger change

**Comment by cason** [comment]
This package was added by #2765. Not sure why they decided to use this precise implementation.

**Comment by cason** [comment]
Overall the code now is kind of confusing with the use of:

-  `crypto/sha256`: standard lib
- `minio/sha256-simd`: possibly improved lib
- `crypto/tmhash`: our own lib, which is a wrapper to `crypto/sha256`

We might consider simplifying this setup.

**Comment by itsdevbear** [comment]
Personally, I like having everywhere in the codebase important from tmhash where tmhash is an alias it whatever library we like. This alias could be changed via build flags for instance.


many to one to few relationship

**Comment by sergio-mena** [comment]
We discussed about this in our internal meeting today. These are the conclusions:

1. We currently don't have performance data that shows an obvious gain in the production setups where CometBFT is used
2. We could gather such performance data ourselves as a due-diligence activity, but we don't have cycles ATM
3. There is an ongoing longer term solution, described in #2241, whereby an app can have CometBFT use custom hashing logic.
    * This longer term solution will render our efforts in point 2 unnecessary

Therefore, we will:

* Use this issue to move all imports of `minio/sha256-simd` (BLS-related code) to `crypto/sha256`
* Wait for #2241 to be completed so that users can do what is suggested in this issue on app-side code

**Comment by cason** [comment]
> Use this issue to move all imports of minio/sha256-simd (BLS-related code) to crypto/sha256

Opened #3071.

**Comment by faddat** [comment]
> We currently don't have performance data that shows an obvious gain in the production setups where CometBFT is used

IDK how much realworldish gain there is, but:

> Support for Intel SHA Extensions

hehe this would make it a lot faster on my homebrew routers which use the J3455 cpu

> Support for AVX512

That's basically "every validator"

**Comment by melekes** [comment]
> IDK how much realworldish gain there is, but:

That's the culprit of this PR 😅

**Comment by melekes** [comment]
Closing as per https://github.com/cometbft/cometbft/pull/2909#issuecomment-2107944974.

**Pull request closed without merging**
